/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author alunolages
 */
public class TelaTreinoAlterar extends javax.swing.JPanel {

    /**
     * Creates new form TelaTreinoAlterar
     */
    public TelaTreinoAlterar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_caixaSemSelec8 = new javax.swing.JLabel();
        lb_caixaSemSelec4 = new javax.swing.JLabel();
        lb_caixaSemSelec3 = new javax.swing.JLabel();
        lb_caixaSemSelec2 = new javax.swing.JLabel();
        lb_caixaSemSelec1 = new javax.swing.JLabel();
        lb_Nome = new javax.swing.JLabel();
        lb_titEndereco = new javax.swing.JLabel();
        lb_titDadosPess = new javax.swing.JLabel();
        lb_logo = new javax.swing.JLabel();
        lb_cliente = new javax.swing.JLabel();
        lb_treino = new javax.swing.JLabel();
        lb_modalidade = new javax.swing.JLabel();
        lb_exercicio = new javax.swing.JLabel();
        lb_instrutor = new javax.swing.JLabel();
        lb_plano = new javax.swing.JLabel();
        lb_sideBar = new javax.swing.JLabel();
        lb_txtAddCliente = new javax.swing.JLabel();
        lb_botaoAddCliente = new javax.swing.JLabel();
        lb_txtCaixa1 = new javax.swing.JLabel();
        lb_txtCaixa2 = new javax.swing.JLabel();
        lb_txtCaixa3 = new javax.swing.JLabel();
        lb_txtCaixa4 = new javax.swing.JLabel();
        lb_txtCaixa5 = new javax.swing.JLabel();
        lb_Nome1 = new javax.swing.JLabel();
        tf_Nome3 = new javax.swing.JTextField();
        cb_CPF = new javax.swing.JComboBox<>();
        lb_Nome2 = new javax.swing.JLabel();
        tf_Nome4 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lb_caixaSemSelec8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixa sem selecao.png"))); // NOI18N
        add(lb_caixaSemSelec8);
        lb_caixaSemSelec8.setBounds(330, 520, 30, 30);

        lb_caixaSemSelec4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixa sem selecao.png"))); // NOI18N
        add(lb_caixaSemSelec4);
        lb_caixaSemSelec4.setBounds(330, 480, 30, 30);

        lb_caixaSemSelec3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixa sem selecao.png"))); // NOI18N
        add(lb_caixaSemSelec3);
        lb_caixaSemSelec3.setBounds(330, 440, 30, 30);

        lb_caixaSemSelec2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixa sem selecao.png"))); // NOI18N
        add(lb_caixaSemSelec2);
        lb_caixaSemSelec2.setBounds(330, 400, 30, 30);

        lb_caixaSemSelec1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixa sem selecao.png"))); // NOI18N
        add(lb_caixaSemSelec1);
        lb_caixaSemSelec1.setBounds(330, 360, 30, 30);

        lb_Nome.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_Nome.setText("Nome Treino:");
        add(lb_Nome);
        lb_Nome.setBounds(330, 150, 180, 30);

        lb_titEndereco.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        lb_titEndereco.setText("Músculo Inclusos");
        add(lb_titEndereco);
        lb_titEndereco.setBounds(330, 330, 320, 20);

        lb_titDadosPess.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        lb_titDadosPess.setText("Adicionar Treino");
        add(lb_titDadosPess);
        lb_titDadosPess.setBounds(330, 130, 170, 20);

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/preto.png"))); // NOI18N
        add(lb_logo);
        lb_logo.setBounds(30, 40, 190, 120);

        lb_cliente.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_cliente.setForeground(new java.awt.Color(0, 0, 0));
        lb_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_cliente.setText("Cliente");
        lb_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_cliente);
        lb_cliente.setBounds(0, 190, 250, 40);

        lb_treino.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lb_treino.setForeground(new java.awt.Color(0, 0, 0));
        lb_treino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_treino.setText("Treino");
        lb_treino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_treino);
        lb_treino.setBounds(0, 490, 250, 40);

        lb_modalidade.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_modalidade.setForeground(new java.awt.Color(0, 0, 0));
        lb_modalidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_modalidade.setText("Modalidade");
        lb_modalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_modalidade);
        lb_modalidade.setBounds(0, 430, 250, 40);

        lb_exercicio.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_exercicio.setForeground(new java.awt.Color(0, 0, 0));
        lb_exercicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exercicio.setText("Exercício");
        lb_exercicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_exercicio);
        lb_exercicio.setBounds(0, 370, 250, 40);

        lb_instrutor.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_instrutor.setForeground(new java.awt.Color(0, 0, 0));
        lb_instrutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_instrutor.setText("Instrutor");
        lb_instrutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_instrutor);
        lb_instrutor.setBounds(0, 250, 250, 40);

        lb_plano.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_plano.setForeground(new java.awt.Color(0, 0, 0));
        lb_plano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_plano.setText("Plano");
        lb_plano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_plano);
        lb_plano.setBounds(0, 310, 250, 40);

        lb_sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sidebar_verde.png"))); // NOI18N
        add(lb_sideBar);
        lb_sideBar.setBounds(0, 0, 254, 720);

        lb_txtAddCliente.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 16)); // NOI18N
        lb_txtAddCliente.setForeground(new java.awt.Color(255, 255, 255));
        lb_txtAddCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_txtAddCliente.setText("ADICIONAR INSTRUTOR");
        add(lb_txtAddCliente);
        lb_txtAddCliente.setBounds(950, 500, 260, 30);

        lb_botaoAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bt-azul.png"))); // NOI18N
        add(lb_botaoAddCliente);
        lb_botaoAddCliente.setBounds(950, 480, 260, 70);

        lb_txtCaixa1.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        lb_txtCaixa1.setForeground(new java.awt.Color(0, 0, 0));
        lb_txtCaixa1.setText("Peito");
        add(lb_txtCaixa1);
        lb_txtCaixa1.setBounds(360, 360, 180, 30);

        lb_txtCaixa2.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        lb_txtCaixa2.setForeground(new java.awt.Color(0, 0, 0));
        lb_txtCaixa2.setText("Costas");
        add(lb_txtCaixa2);
        lb_txtCaixa2.setBounds(360, 400, 180, 30);

        lb_txtCaixa3.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        lb_txtCaixa3.setForeground(new java.awt.Color(0, 0, 0));
        lb_txtCaixa3.setText("Braço");
        add(lb_txtCaixa3);
        lb_txtCaixa3.setBounds(360, 440, 180, 30);

        lb_txtCaixa4.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        lb_txtCaixa4.setForeground(new java.awt.Color(0, 0, 0));
        lb_txtCaixa4.setText("Perna");
        add(lb_txtCaixa4);
        lb_txtCaixa4.setBounds(360, 480, 180, 30);

        lb_txtCaixa5.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        lb_txtCaixa5.setForeground(new java.awt.Color(0, 0, 0));
        lb_txtCaixa5.setText("Ombro");
        add(lb_txtCaixa5);
        lb_txtCaixa5.setBounds(360, 520, 180, 30);

        lb_Nome1.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_Nome1.setText("Selecione um dia da semana:");
        add(lb_Nome1);
        lb_Nome1.setBounds(330, 230, 250, 30);

        tf_Nome3.setBackground(new java.awt.Color(238, 238, 238));
        tf_Nome3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tf_Nome3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_Nome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_Nome3ActionPerformed(evt);
            }
        });
        add(tf_Nome3);
        tf_Nome3.setBounds(330, 260, 320, 40);

        cb_CPF.setBackground(new java.awt.Color(153, 255, 51));
        cb_CPF.setFont(new java.awt.Font("CommercialScript BT", 1, 14)); // NOI18N
        cb_CPF.setForeground(new java.awt.Color(0, 0, 0));
        cb_CPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cb_CPF);
        cb_CPF.setBounds(330, 180, 320, 40);

        lb_Nome2.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_Nome2.setText("Para qual dia vai alterar:");
        add(lb_Nome2);
        lb_Nome2.setBounds(700, 230, 250, 30);

        tf_Nome4.setBackground(new java.awt.Color(238, 238, 238));
        tf_Nome4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tf_Nome4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_Nome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_Nome4ActionPerformed(evt);
            }
        });
        add(tf_Nome4);
        tf_Nome4.setBounds(700, 260, 320, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_Nome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_Nome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Nome3ActionPerformed

    private void tf_Nome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_Nome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Nome4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_CPF;
    private javax.swing.JLabel lb_Nome;
    private javax.swing.JLabel lb_Nome1;
    private javax.swing.JLabel lb_Nome2;
    private javax.swing.JLabel lb_botaoAddCliente;
    private javax.swing.JLabel lb_caixaSemSelec1;
    private javax.swing.JLabel lb_caixaSemSelec2;
    private javax.swing.JLabel lb_caixaSemSelec3;
    private javax.swing.JLabel lb_caixaSemSelec4;
    private javax.swing.JLabel lb_caixaSemSelec8;
    private javax.swing.JLabel lb_cliente;
    private javax.swing.JLabel lb_exercicio;
    private javax.swing.JLabel lb_instrutor;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_modalidade;
    private javax.swing.JLabel lb_plano;
    private javax.swing.JLabel lb_sideBar;
    private javax.swing.JLabel lb_titDadosPess;
    private javax.swing.JLabel lb_titEndereco;
    private javax.swing.JLabel lb_treino;
    private javax.swing.JLabel lb_txtAddCliente;
    private javax.swing.JLabel lb_txtCaixa1;
    private javax.swing.JLabel lb_txtCaixa2;
    private javax.swing.JLabel lb_txtCaixa3;
    private javax.swing.JLabel lb_txtCaixa4;
    private javax.swing.JLabel lb_txtCaixa5;
    private javax.swing.JTextField tf_Nome3;
    private javax.swing.JTextField tf_Nome4;
    // End of variables declaration//GEN-END:variables
}
