/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author tiovi
 */
public class TelaInstrutorAdicionar extends javax.swing.JPanel {

    /**
     * Creates new form TelaAddInstrutor
     */
    public TelaInstrutorAdicionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_Nome = new javax.swing.JTextField();
        lb_dataNasc = new javax.swing.JLabel();
        lb_CPF = new javax.swing.JLabel();
        lb_Nome = new javax.swing.JLabel();
        lb_titPlano = new javax.swing.JLabel();
        lb_titEndereco = new javax.swing.JLabel();
        lb_titDadosPess = new javax.swing.JLabel();
        lb_cliente = new javax.swing.JLabel();
        lb_logo = new javax.swing.JLabel();
        lb_treino = new javax.swing.JLabel();
        lb_modalidade = new javax.swing.JLabel();
        lb_instrutor = new javax.swing.JLabel();
        lb_plano = new javax.swing.JLabel();
        lb_sideBar = new javax.swing.JLabel();
        lb_tipoPlano = new javax.swing.JLabel();
        lb_txtAddCliente = new javax.swing.JLabel();
        lb_botaoAddCliente = new javax.swing.JLabel();
        tf_rua = new javax.swing.JTextField();
        cb_tipoPlano = new javax.swing.JComboBox<>();
        ftf_cpf = new javax.swing.JFormattedTextField();
        ftf_dataNasc2 = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setRequestFocusEnabled(false);
        setLayout(null);

        tf_Nome.setBackground(new java.awt.Color(238, 238, 238));
        tf_Nome.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tf_Nome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NomeActionPerformed(evt);
            }
        });
        add(tf_Nome);
        tf_Nome.setBounds(330, 210, 320, 40);

        lb_dataNasc.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_dataNasc.setText("Data de Nascimento:");
        add(lb_dataNasc);
        lb_dataNasc.setBounds(670, 180, 200, 30);

        lb_CPF.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_CPF.setText("CPF:");
        add(lb_CPF);
        lb_CPF.setBounds(330, 260, 80, 20);

        lb_Nome.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_Nome.setText("Nome:");
        add(lb_Nome);
        lb_Nome.setBounds(330, 180, 80, 30);

        lb_titPlano.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        lb_titPlano.setText("Modalidade");
        add(lb_titPlano);
        lb_titPlano.setBounds(330, 450, 170, 20);

        lb_titEndereco.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        lb_titEndereco.setText("Formação");
        add(lb_titEndereco);
        lb_titEndereco.setBounds(330, 350, 170, 20);

        lb_titDadosPess.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        lb_titDadosPess.setText("Dados Pessoais");
        add(lb_titDadosPess);
        lb_titDadosPess.setBounds(330, 160, 170, 20);

        lb_cliente.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lb_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_cliente.setText("Cliente");
        lb_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_cliente);
        lb_cliente.setBounds(0, 220, 250, 40);

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/preto.png"))); // NOI18N
        add(lb_logo);
        lb_logo.setBounds(30, 40, 190, 120);

        lb_treino.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_treino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_treino.setText("Treino");
        lb_treino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_treino);
        lb_treino.setBounds(0, 460, 250, 40);

        lb_modalidade.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_modalidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_modalidade.setText("Modalidade");
        lb_modalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_modalidade);
        lb_modalidade.setBounds(0, 400, 250, 40);

        lb_instrutor.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_instrutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_instrutor.setText("Instrutor");
        lb_instrutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_instrutor);
        lb_instrutor.setBounds(0, 280, 250, 40);

        lb_plano.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_plano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_plano.setText("Plano");
        lb_plano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lb_plano);
        lb_plano.setBounds(0, 340, 250, 40);

        lb_sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sidebar_verde.png"))); // NOI18N
        add(lb_sideBar);
        lb_sideBar.setBounds(0, 0, 254, 720);

        lb_tipoPlano.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_tipoPlano.setText("Tipo de Modalidade:");
        add(lb_tipoPlano);
        lb_tipoPlano.setBounds(330, 480, 230, 30);

        lb_txtAddCliente.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 16)); // NOI18N
        lb_txtAddCliente.setForeground(new java.awt.Color(255, 255, 255));
        lb_txtAddCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_txtAddCliente.setText("ADICIONAR INSTRUTOR");
        add(lb_txtAddCliente);
        lb_txtAddCliente.setBounds(970, 600, 260, 30);

        lb_botaoAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bt-azul.png"))); // NOI18N
        add(lb_botaoAddCliente);
        lb_botaoAddCliente.setBounds(970, 580, 260, 70);

        tf_rua.setBackground(new java.awt.Color(238, 238, 238));
        tf_rua.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tf_rua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ruaActionPerformed(evt);
            }
        });
        add(tf_rua);
        tf_rua.setBounds(330, 380, 320, 40);

        cb_tipoPlano.setBackground(new java.awt.Color(235, 235, 235));
        cb_tipoPlano.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        cb_tipoPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cb_tipoPlano);
        cb_tipoPlano.setBounds(330, 510, 300, 40);

        ftf_cpf.setBackground(new java.awt.Color(228, 228, 228));
        ftf_cpf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            ftf_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(ftf_cpf);
        ftf_cpf.setBounds(330, 280, 320, 40);

        ftf_dataNasc2.setBackground(new java.awt.Color(228, 228, 228));
        ftf_dataNasc2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ftf_dataNasc2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        add(ftf_dataNasc2);
        ftf_dataNasc2.setBounds(670, 210, 200, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NomeActionPerformed

    private void tf_ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ruaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_tipoPlano;
    private javax.swing.JFormattedTextField ftf_cpf;
    private javax.swing.JFormattedTextField ftf_dataNasc2;
    private javax.swing.JLabel lb_CPF;
    private javax.swing.JLabel lb_Nome;
    private javax.swing.JLabel lb_botaoAddCliente;
    private javax.swing.JLabel lb_cliente;
    private javax.swing.JLabel lb_dataNasc;
    private javax.swing.JLabel lb_instrutor;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_modalidade;
    private javax.swing.JLabel lb_plano;
    private javax.swing.JLabel lb_sideBar;
    private javax.swing.JLabel lb_tipoPlano;
    private javax.swing.JLabel lb_titDadosPess;
    private javax.swing.JLabel lb_titEndereco;
    private javax.swing.JLabel lb_titPlano;
    private javax.swing.JLabel lb_treino;
    private javax.swing.JLabel lb_txtAddCliente;
    private javax.swing.JTextField tf_Nome;
    private javax.swing.JTextField tf_rua;
    // End of variables declaration//GEN-END:variables
}
